// app/layout.tsx
import "./globals.css";
import { Noto_Sans_JP, Poppins, MuseoModerno } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";

// フォント読み込み
const notojp = Noto_Sans_JP({
  subsets: ["latin", "latin-ext", "latin"],
  weight: ["400", "700"],
  variable: "--font-notojp",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const museo = MuseoModerno({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-museo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Scrapt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notojp.variable} ${poppins.variable} ${museo.variable}`}>
      <body className="font-notojp flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">{children}</main>
      <Footer />
      </body>
    </html>
  );
}
